services:
  postgres:
    image: postgres:18
    container_name: gestion_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./gC_postgreSql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_privada
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/gestion-compras
    container_name: gestion_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gestion_postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pdf_data:${PDF_STORAGE_PATH}
    networks:
      - red_privada
      - red_publica
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: gestion_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - red_publica

volumes:
  postgres_data:
  pdf_data:

networks:
  red_privada:
    driver: bridge
  red_publica:
    driver: bridge